version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/build:/build
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
    build: .
    container_name: md01
    volumes:
      - ./src:/src
    expose:
      - "8088"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
