version: '2'  
services:  
  nginx:
    build: ./frontend
    container_name: ng01
    ports:
      - "8000:8000"
    depends_on:
      - web
  web:
    build: ./backend
    container_name: md01
    expose:
      - "8088"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
